services:
  client-service:
    image: client-service:latest
    container_name: client-service
    env_file:
      - .env.client
    ports:
      - "17001:8080"
    networks:
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: main
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
    working_dir: /app
networks:
  my-internal-net:
    external: true
