services:
  eureka-server-service:
    image: eureka-server-service:latest
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    networks: # 네트워크 설정
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: main
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
      working_dir: /app
networks:
  my-internal-net:
    external: true