services:
  ainews-service:
    image: ainews-service:latest
    container_name: ainews-service
    env_file:
      - .env.ainews
    ports:
      - "16001:16001"
    networks: # 네트워크 설정
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
      working_dir: /app
networks:
  my-internal-net:
    external: true