services:
  comment-service:
    image: comment-service:latest
    container_name: comment-service
    env_file:
      - .env.comment
    ports:
      - "12001:12001"
    networks: # 네트워크 설정
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
      working_dir: /app
    volumes:
      - ./logs:/app/comment/logs
networks:
  my-internal-net:
    external: true