services:
  comment-service:
    image: gateway-service:latest
    container_name: gateway-service
    env_file:
      - .env.gateway
    ports:
      - "8080:8080"
    networks: # 네트워크 설정
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
      working_dir: /app
networks:
  my-internal-net:
    external: true