server:
  port: 15001
spring:
  config:
    import:
      - file:.env.newsorigin[.properties]
  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        format_sql: true
app:
  client:
    naver:
      host: ${DEVELOP_NAVER_HOST}
      collect-news:
        id: ${DEVELOP_NAVER_COLLECT_NEWS_ID}
        key: ${DEVELOP_NAVER_COLLECT_NEWS_KEY}
        path: ${DEVELOP_NAVER_COLLECT_NEWS_PATH}
        # 최대한 한번에 검색이 많이 되도록 하기 위해 가장 많이 등장하는 단어로 검색
        search-query: ${DEVELOP_NAVER_COLLECT_NEWS_SEARCH_QUERY}
        # 정렬 기준 : date(날짜순 내림차순) or sim(정확도 내림차순)
        search-sort: ${DEVELOP_NAVER_COLLECT_NEWS_SEARCH_SORT}
        # 한번에 쿼리할 양
        search-display: ${DEVELOP_NAVER_COLLECT_NEWS_SEARCH_DISPLAY}
