services:
  news-service:
    build:
      context: .         # news/ 폴더 (JAR 있는 곳 기준)
      dockerfile: Dockerfile
    container_name: news-main-app
    ports:
      - "11001:8080"
    env_file:
      - .env.news
    environment:
      SPRING_PROFILES_ACTIVE: main



