services:
  news-service:
    build:
      context: .         # news/ 폴더 (JAR 있는 곳 기준)
      dockerfile: Dockerfile
    container_name: news-main-app
    ports:
      - "11001:8080"
    env_file:
      - .env.news
    environment:
      SPRING_PROFILES_ACTIVE: main
    networks: # 네트워크 설정
      - my-internal-net
      environment:
        TZ: Asia/Seoul
        SPRING_PROFILES_ACTIVE: main
        JAVA_OPTS: >-
          -Duser.timezone=Asia/Seoul
        working_dir: /app
    networks:
      my-internal-net:
        external: true
