server:
  port: 11001

spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers} # EmbeddedKafka 사용 시 필수
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          default_batch_fetch_size: 100
          format_sql: true
