server:
  port: 11001

eureka:
  instance:
    hostname: ${DEVELOP_EUREKA_HOSTNAME}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    appname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: news-service
  config:
    import:
      - file:.env.news[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 20
      max-poll-interval-ms: 15000
      heartbeat-interval-ms: 1000
      session-timeout-ms: 60000

    listener:
      ack-mode: manual_immediate

  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /doc
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
