server:
  port: 11001

#eureka:
#  client:
#    enabled: false

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 20
      max-poll-interval-ms: 15000
      heartbeat-interval-ms: 1000
      session-timeout-ms: 60000

    listener:
      ack-mode: manual_immediate

  datasource:
    url: jdbc:mysql://localhost:3306/newpick4u
    username: usernewpick4u
    password: usernewpick4u
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /doc
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
