server:
  port: 11001

spring:
  config:
    import:
      - file:.env.news

  kafka:
    bootstrap-servers:  ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.newpick4u.news.news.infrastructure.kafka.dto'
        spring.json.value.default.type: com.newpick4u.news.news.infrastructure.kafka.dto.AiNewsDto
      max-poll-records: 20
      max-poll-interval-ms: 15000
      heartbeat-interval-ms: 1000
      session-timeout-ms: 60000

    listener:
      ack-mode: manual_immediate

    datasource:
      url: ${DEVELOP_DB_URL}
      username: ${DEVELOP_DB_USERNAME}
      password: ${DEVELOP_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        open-in-view: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            default_batch_fetch_size: 100
            format_sql: true
