services:
  tag-service:
    image: tag-service:latest
    container_name: tag-service
    env_file:
      - .env.tag
    ports:
      - "14001:14001"
    networks: # 네트워크 설정
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: main
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
      working_dir: /app
networks:
  my-internal-net:
    external: true