server:
  port: 13001

eureka:
  instance:
    hostname: ${DEVELOP_EUREKA_HOSTNAME}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    appname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  config:
    import:
      - file:.env.thread[.properties]
  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        format_sql: true

  data:
    redis:
      host: ${DEVELOP_REDIS_HOST}
      port: ${DEVELOP_REDIS_PORT}
      password: ${DEVELOP_REDIS_PASSWORD}

gemini:
  url: ${GEMINI_URL}