services:
  comment-service:
    image: user-service:latest
    container_name: user-service
    env_file:
      - .env.user
    ports:
      - "10001:10001"
    networks: # 네트워크 설정
      - my-internal-net
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: >-
        -Duser.timezone=Asia/Seoul
      working_dir: /app
networks:
  my-internal-net:
    external: true